load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

exports_files(["dependency.pyi"])

py_library(
    name = "py_dependency",
    srcs = ["dependency.py"],
)
